(function(){
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  function setHomeHeader(){const t=$('#pageTitle'),s=$('#pageSub');if(t)t.textContent='الصفحة الرئيسية';if(s)s.textContent='مرحبًا بك في منصة اجتماعات جمعية الإحسان';}
  function readDb(){try{return JSON.parse(localStorage.getItem('ehsan_meetings_v2')||'{}')}catch{return{}}}
  function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function formatDate(v){if(!v)return'—';try{return new Date(v).toLocaleDateString('ar-SA-u-ca-gregory',{year:'numeric',month:'short',day:'numeric'})}catch{return v}}
  function renderHome(){const db=readDb(),meetings=db.meetings||[],tasks=db.tasks||[],minutes=db.minutes||[],notifications=db.notifications||[],now=new Date().toISOString().slice(0,10);const upcoming=meetings.filter(m=>m.date>=now&&m.status!=='مكتمل').sort((a,b)=>(a.date||'').localeCompare(b.date||'')).slice(0,4),unread=notifications.filter(n=>!n.read);if($('#homeMeetings'))$('#homeMeetings').textContent=meetings.filter(m=>m.date>=now&&m.status!=='مكتمل').length;if($('#homeNotifications'))$('#homeNotifications').textContent=unread.length;if($('#homeTasks'))$('#homeTasks').textContent=tasks.filter(t=>t.status!=='مكتملة').length;if($('#homeMinutes'))$('#homeMinutes').textContent=minutes.filter(m=>m.signed).length;const ul=$('#homeUpcomingList');if(ul)ul.innerHTML=upcoming.length?upcoming.map(m=>`<div class="list-item"><strong>${escapeHtml(m.title||'اجتماع')}</strong><div class="meta"><span>${formatDate(m.date)}</span><span>${escapeHtml(m.time||'')}</span><span>${escapeHtml(m.committee||'')}</span></div></div>`).join(''):'<div class="list-item">لا توجد اجتماعات قادمة. يمكنك إنشاء اجتماع جديد من الصفحة الرئيسية.</div>';const nl=$('#homeRecentNotifications');if(nl)nl.innerHTML=unread.slice().reverse().slice(0,4).map(n=>`<div class="list-item"><strong>${escapeHtml(n.title||'إشعار')}</strong><p>${escapeHtml(n.body||'')}</p></div>`).join('')||'<div class="list-item">لا توجد تنبيهات جديدة.</div>'}
  $$('[data-view="home"],[data-view-jump="home"]').forEach(el=>el.addEventListener('click',()=>setTimeout(()=>{setHomeHeader();renderHome()},0)));
  const brand=$('.brand-box[data-view-jump="home"]');if(brand)brand.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();brand.click()}});
  window.addEventListener('storage',renderHome);setInterval(renderHome,2000);setHomeHeader();renderHome();
})();