const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='ehsan_meetings_v2';
const seed={members:[{id:1,name:'رئيس مجلس الإدارة',role:'رئيس المجلس',phone:'05XXXXXXXX',email:'chair@example.org',job:'رئيس مجلس الإدارة',joined:'2026-01-01'}],committees:[{id:1,name:'مجلس الإدارة',type:'مجلس',chair:'رئيس مجلس الإدارة'},{id:2,name:'اللجنة التنفيذية',type:'لجنة',chair:''},{id:3,name:'لجنة استثمار الموارد المالية',type:'لجنة',chair:''},{id:4,name:'لجنة الخدمات الرعوية',type:'لجنة',chair:''},{id:5,name:'لجنة الترشيحات',type:'لجنة',chair:''},{id:6,name:'لجنة المراجعة الداخلية',type:'لجنة',chair:''}],meetings:[],votes:[],minutes:[],tasks:[],notifications:[{id:1,title:'مرحبًا بك في منصة الاجتماعات',body:'يمكنك الآن إنشاء الاجتماعات وإدارة اللجان والقرارات من لوحة واحدة.',date:new Date().toISOString(),read:false}],mail:[{id:1,box:'inbox',from:'إدارة المنصة',to:'مدير النظام',subject:'تفعيل النسخة التجريبية',body:'تم تفعيل النسخة الثانية من منصة الاجتماعات.',date:new Date().toISOString()}]};
let db=load();let selectedFiles=[];let modalAction=null;let currentMailbox='inbox';
function load(){try{return {...structuredClone(seed),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function uid(arr){return Math.max(0,...arr.map(x=>+x.id||0))+1}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(v){if(!v)return'—';try{return new Date(v).toLocaleDateString('ar-SA-u-ca-gregory',{year:'numeric',month:'short',day:'numeric'})}catch{return v}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
const titles={dashboard:['لوحة التحكم','نظرة شاملة على اجتماعات المجلس واللجان'],meetings:['الاجتماعات','السجل الكامل للاجتماعات'], 'new-meeting':['اجتماع جديد','جدولة الاجتماع وإدارة جدول الأعمال والمرفقات'],members:['إدارة الأعضاء','بيانات أعضاء المجلس واللجان'],committees:['اللجان','إدارة اللجان المنبثقة من المجلس'],votes:['التصويت والنصاب','توثيق التصويت وحساب نسبة الحضور'],minutes:['المحاضر والتوقيع','اعتماد المحاضر والتوقيع الإلكتروني'],tasks:['القرارات والمهام','متابعة تنفيذ القرارات والتوصيات'],notifications:['الإشعارات','تذكيرات الحضور والتصويت والتوقيع'],mail:['البريد الوارد والصادر','مراسلات الأعضاء الداخلية']};
function showView(v){$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+v)?.classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#pageTitle').textContent=titles[v]?.[0]||'';$('#pageSub').textContent=titles[v]?.[1]||'';$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-view-jump]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewJump)));$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
function renderAll(){renderStats();renderMeetings();renderMembers();renderCommittees();renderSelects();renderVotes();renderMinutes();renderTasks();renderNotifications();renderMail()}
function renderStats(){const now=new Date().toISOString().slice(0,10);$('#statMeetings').textContent=db.meetings.filter(m=>m.date>=now&&m.status!=='مكتمل').length;$('#statMembers').textContent=db.members.length;$('#statTasks').textContent=db.tasks.filter(t=>t.status!=='مكتملة').length;$('#statSigned').textContent=db.minutes.filter(m=>m.signed).length;const up=[...db.meetings].filter(m=>m.date>=now).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4);$('#upcomingList').innerHTML=up.length?up.map(m=>`<div class="list-item"><strong>${esc(m.title)}</strong><div class="meta"><span>${fmtDate(m.date)}</span><span>${esc(m.time)}</span><span>${esc(m.committee)}</span></div></div>`).join(''):'<div class="list-item">لا توجد اجتماعات قادمة. ابدأ بإنشاء اجتماع جديد.</div>';const ns=[...db.notifications].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4);$('#recentNotifications').innerHTML=ns.map(n=>`<div class="list-item"><strong>${esc(n.title)}</strong><div class="meta">${new Date(n.date).toLocaleString('ar-SA')}</div></div>`).join('')||'<div class="list-item">لا توجد إشعارات.</div>'}
function renderMeetings(){const q=($('#meetingSearch')?.value||'').toLowerCase(),f=$('#meetingFilter')?.value||'all';let items=db.meetings.filter(m=>(f==='all'||m.status===f)&&(`${m.title} ${m.committee}`).toLowerCase().includes(q));$('#meetingsTable').innerHTML=items.length?items.map(m=>`<tr><td><strong>${esc(m.title)}</strong></td><td>${esc(m.committee)}</td><td>${fmtDate(m.date)}</td><td>${esc(m.time)}</td><td>${esc(m.mode)}</td><td><span class="status-pill ${m.status==='مكتمل'?'good':m.status==='مجدول'?'warn':''}">${esc(m.status)}</span></td><td>${m.files?.length||0}</td><td><button class="link-btn" onclick="openMeeting(${m.id})">عرض</button> · <button class="link-btn" onclick="deleteMeeting(${m.id})">حذف</button></td></tr>`).join(''):'<tr><td colspan="8">لا توجد اجتماعات مطابقة.</td></tr>'}
$('#meetingSearch').addEventListener('input',renderMeetings);$('#meetingFilter').addEventListener('change',renderMeetings);
window.deleteMeeting=id=>{if(confirm('حذف الاجتماع؟')){db.meetings=db.meetings.filter(x=>x.id!==id);save();toast('تم حذف الاجتماع')}};
window.openMeeting=id=>{const m=db.meetings.find(x=>x.id===id);if(!m)return;openModal('تفاصيل الاجتماع',`<div class="list"><div class="list-item"><strong>${esc(m.title)}</strong><div class="meta"><span>${fmtDate(m.date)}</span><span>${esc(m.hijri||'')}</span><span>${esc(m.time)} - ${esc(m.endTime||'')}</span><span>${esc(m.mode)}</span></div></div><div class="list-item"><b>الموقع:</b> ${esc(m.location||'—')}<br><b>المنصة:</b> ${esc(m.platform||'—')}<br>${m.meetingUrl?`<b>الرابط:</b> <a href="${esc(m.meetingUrl)}" target="_blank">فتح الاجتماع</a>`:''}</div><div class="list-item"><b>جدول الأعمال</b><ol>${(m.agenda||[]).map(a=>`<li>${esc(a.title)} ${a.owner?`— ${esc(a.owner)}`:''}</li>`).join('')}</ol></div><div class="list-item"><b>المرفقات</b><div class="chips">${(m.files||[]).map(f=>`<span class="chip">📎 ${esc(f.name)}</span>`).join('')||'لا يوجد'}</div></div></div>`,null,false)};
function renderMembers(){$('#membersGrid').innerHTML=db.members.map(m=>`<article><div class="member-head"><div class="member-avatar">${esc(m.name.slice(0,1))}</div><div><strong>${esc(m.name)}</strong><div class="meta">${esc(m.role||'عضو')}</div></div></div><p>📱 ${esc(m.phone||'—')}<br>✉ ${esc(m.email||'—')}<br>💼 ${esc(m.job||'—')}</p><div class="card-actions"><button class="btn small ghost" onclick="editMember(${m.id})">تعديل</button><button class="btn small ghost" onclick="removeMember(${m.id})">حذف</button></div></article>`).join('')||'<article>لا يوجد أعضاء.</article>'}
function renderCommittees(){$('#committeesGrid').innerHTML=db.committees.map(c=>`<article><div class="committee-head"><div class="member-avatar">${esc(c.name.slice(0,1))}</div><div><strong>${esc(c.name)}</strong><div class="meta">${esc(c.type||'لجنة')}</div></div></div><p>الرئيس: ${esc(c.chair||'غير محدد')}</p><div class="card-actions"><button class="btn small ghost" onclick="editCommittee(${c.id})">تعديل</button><button class="btn small ghost" onclick="removeCommittee(${c.id})">حذف</button></div></article>`).join('')}
function renderSelects(){const co=db.committees.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('');$('#meetingCommittee').innerHTML=co;const mo='<option value="">اختر الاجتماع</option>'+db.meetings.map(m=>`<option value="${m.id}">${esc(m.title)}</option>`).join('');$('#voteMeeting').innerHTML=mo;$('#minutesMeeting').innerHTML=mo}
function field(label,name,type='text',val=''){return`<label>${label}<input id="mf_${name}" type="${type}" value="${esc(val)}" /></label>`}
function openModal(title,html,onSave,showSave=true){$('#modalTitle').textContent=title;$('#modalFields').innerHTML=html;modalAction=onSave;$('#modalSave').style.display=showSave?'inline-flex':'none';$('#genericModal').showModal()}
$('#modalSave').addEventListener('click',()=>{if(modalAction)modalAction();$('#genericModal').close()});
$('#addMemberBtn').addEventListener('click',()=>openModal('إضافة عضو',field('الاسم','name')+field('رقم الهوية','national')+field('رقم الجوال','phone')+field('البريد الإلكتروني','email','email')+field('المسمى الوظيفي','job')+field('جهة العمل','org')+field('تاريخ الميلاد','dob','date')+field('تاريخ الالتحاق','joined','date'),()=>{db.members.push({id:uid(db.members),name:$('#mf_name').value||'عضو جديد',national:$('#mf_national').value,phone:$('#mf_phone').value,email:$('#mf_email').value,job:$('#mf_job').value,org:$('#mf_org').value,dob:$('#mf_dob').value,joined:$('#mf_joined').value,role:'عضو'});save();toast('تمت إضافة العضو')}));
window.editMember=id=>{const m=db.members.find(x=>x.id===id);openModal('تعديل عضو',field('الاسم','name','text',m.name)+field('الجوال','phone','text',m.phone)+field('البريد','email','email',m.email)+field('المسمى','job','text',m.job),()=>{m.name=$('#mf_name').value;m.phone=$('#mf_phone').value;m.email=$('#mf_email').value;m.job=$('#mf_job').value;save();toast('تم تحديث العضو')})};window.removeMember=id=>{if(confirm('حذف العضو؟')){db.members=db.members.filter(x=>x.id!==id);save()}};
$('#addCommitteeBtn').addEventListener('click',()=>openModal('لجنة جديدة',field('اسم اللجنة','name')+field('رئيس اللجنة','chair'),()=>{db.committees.push({id:uid(db.committees),name:$('#mf_name').value||'لجنة جديدة',chair:$('#mf_chair').value,type:'لجنة'});save();toast('تمت إضافة اللجنة')}));window.editCommittee=id=>{const c=db.committees.find(x=>x.id===id);openModal('تعديل اللجنة',field('اسم اللجنة','name','text',c.name)+field('رئيس اللجنة','chair','text',c.chair),()=>{c.name=$('#mf_name').value;c.chair=$('#mf_chair').value;save()})};window.removeCommittee=id=>{if(confirm('حذف اللجنة؟')){db.committees=db.committees.filter(x=>x.id!==id);save()}};
function addAgendaRow(v={}){const wrap=$('#agendaRows'),n=wrap.children.length+1;const row=document.createElement('div');row.className='agenda-row';row.innerHTML=`<div class="agenda-number">${n}</div><input class="agenda-title" placeholder="موضوع المحور" value="${esc(v.title||'')}"/><input class="agenda-owner" placeholder="المسؤول / الزمن" value="${esc(v.owner||'')}"/><button type="button" class="remove-btn">✕</button>`;row.querySelector('.remove-btn').onclick=()=>{row.remove();$$('.agenda-number',wrap).forEach((x,i)=>x.textContent=i+1)};wrap.appendChild(row)}
$('#addAgenda').addEventListener('click',()=>addAgendaRow());addAgendaRow();
$('#meetingFiles').addEventListener('change',e=>{selectedFiles=[...e.target.files].map(f=>({name:f.name,size:f.size,type:f.type}));$('#filePreview').innerHTML=selectedFiles.map(f=>`<span class="chip">📎 ${esc(f.name)}</span>`).join('')});
$('#meetingForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),agenda=$$('.agenda-row').map(r=>({title:$('.agenda-title',r).value,owner:$('.agenda-owner',r).value})).filter(a=>a.title);db.meetings.push({id:uid(db.meetings),title:fd.get('title'),committee:fd.get('committee'),date:fd.get('date'),hijri:fd.get('hijri'),time:fd.get('time'),endTime:fd.get('endTime'),mode:fd.get('mode'),location:fd.get('location'),platform:fd.get('platform'),meetingUrl:fd.get('meetingUrl'),description:fd.get('description'),agenda,files:selectedFiles,status:'مجدول'});db.notifications.push({id:uid(db.notifications),title:'تم جدولة اجتماع جديد',body:`${fd.get('title')} — ${fd.get('date')} ${fd.get('time')}`,date:new Date().toISOString(),read:false});selectedFiles=[];e.currentTarget.reset();$('#filePreview').innerHTML='';$('#agendaRows').innerHTML='';addAgendaRow();save();toast('تم حفظ الاجتماع وجدولته');showView('meetings')});
$('#voteForm').addEventListener('submit',e=>{e.preventDefault();const total=+$('#voteTotal').value||1,present=+$('#votePresent').value||0;db.votes.push({id:uid(db.votes),meetingId:+$('#voteMeeting').value,title:$('#voteTitle').value,type:$('#voteType').value,present,total,yes:+$('#voteYes').value||0,no:+$('#voteNo').value||0,abstain:+$('#voteAbstain').value||0,date:new Date().toISOString()});save();e.currentTarget.reset();toast('تم حفظ نتيجة التصويت')});
function renderVotes(){$('#votesList').innerHTML=[...db.votes].reverse().map(v=>{const m=db.meetings.find(x=>x.id===v.meetingId);const pct=Math.round((v.present/v.total)*100);return`<div class="list-item"><strong>${esc(v.title)}</strong><div class="meta"><span>${esc(m?.title||'')}</span><span>النصاب: ${pct}%</span><span>موافق ${v.yes}</span><span>غير موافق ${v.no}</span><span>ممتنع ${v.abstain}</span></div></div>`}).join('')||'<div class="list-item">لا توجد تصويتات بعد.</div>'}
let ctx,draw=false;function initCanvas(){const c=$('#signatureCanvas');ctx=c.getContext('2d');ctx.lineWidth=2.4;ctx.lineCap='round';ctx.strokeStyle='#2f2926';const pos=e=>{const r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*(c.width/r.width),y:(p.clientY-r.top)*(c.height/r.height)}};['mousedown','touchstart'].forEach(ev=>c.addEventListener(ev,e=>{draw=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()}));['mousemove','touchmove'].forEach(ev=>c.addEventListener(ev,e=>{if(!draw)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()}));['mouseup','mouseleave','touchend'].forEach(ev=>c.addEventListener(ev,()=>draw=false))}initCanvas();
$('#clearSignature').onclick=()=>ctx.clearRect(0,0,620,180);$('#signatureUpload').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const img=new Image();img.onload=()=>{ctx.clearRect(0,0,620,180);ctx.drawImage(img,0,0,620,180)};img.src=URL.createObjectURL(f)});
$('#minutesForm').addEventListener('submit',e=>{e.preventDefault();const c=$('#signatureCanvas');db.minutes.push({id:uid(db.minutes),meetingId:+$('#minutesMeeting').value,text:$('#minutesText').value,improvement:$('#minutesImprovement').value,signature:c.toDataURL('image/png'),signed:true,date:new Date().toISOString()});const m=db.meetings.find(x=>x.id===+$('#minutesMeeting').value);if(m)m.status='مكتمل';db.notifications.push({id:uid(db.notifications),title:'تم اعتماد محضر اجتماع',body:m?.title||'محضر اجتماع',date:new Date().toISOString(),read:false});ctx.clearRect(0,0,620,180);e.currentTarget.reset();save();toast('تم حفظ واعتماد المحضر')});
function renderMinutes(){$('#minutesList').innerHTML=[...db.minutes].reverse().map(x=>{const m=db.meetings.find(y=>y.id===x.meetingId);return`<div class="list-item"><strong>${esc(m?.title||'اجتماع')}</strong><div class="meta"><span>${fmtDate(x.date)}</span><span class="status-pill good">موقّع</span></div><p>${esc(x.text).slice(0,160)}${x.text.length>160?'...':''}</p></div>`}).join('')||'<div class="list-item">لا توجد محاضر محفوظة.</div>'}
$('#addTaskBtn').addEventListener('click',()=>openModal('مهمة جديدة',field('عنوان المهمة','title')+field('المسؤول','owner')+field('تاريخ الاستحقاق','due','date'),()=>{db.tasks.push({id:uid(db.tasks),title:$('#mf_title').value||'مهمة',owner:$('#mf_owner').value,due:$('#mf_due').value,status:'جديدة'});save();toast('تمت إضافة المهمة')}));
function renderTasks(){const map={'جديدة':'tasks-new','قيد التنفيذ':'tasks-progress','مكتملة':'tasks-done'};Object.values(map).forEach(id=>$('#'+id).innerHTML='');db.tasks.forEach(t=>{$('#'+map[t.status]).insertAdjacentHTML('beforeend',`<div class="task-card"><strong>${esc(t.title)}</strong><small>المسؤول: ${esc(t.owner||'—')} · الاستحقاق: ${fmtDate(t.due)}</small><div class="card-actions">${t.status!=='قيد التنفيذ'?`<button class="btn small ghost" onclick="moveTask(${t.id},'قيد التنفيذ')">قيد التنفيذ</button>`:''}${t.status!=='مكتملة'?`<button class="btn small ghost" onclick="moveTask(${t.id},'مكتملة')">إكمال</button>`:''}<button class="btn small ghost" onclick="deleteTask(${t.id})">حذف</button></div></div>`)})}window.moveTask=(id,s)=>{const t=db.tasks.find(x=>x.id===id);if(t){t.status=s;save()}};window.deleteTask=id=>{db.tasks=db.tasks.filter(x=>x.id!==id);save()};
$('#addNotifBtn').addEventListener('click',()=>openModal('إشعار جديد',field('العنوان','title')+'<label>النص<textarea id="mf_body" rows="4"></textarea></label>',()=>{db.notifications.push({id:uid(db.notifications),title:$('#mf_title').value||'إشعار',body:$('#mf_body').value,date:new Date().toISOString(),read:false});save();toast('تم إنشاء الإشعار')}));
function renderNotifications(){const unread=db.notifications.filter(n=>!n.read).length;$('#notifBadge').textContent=unread;$('#notificationsList').innerHTML=[...db.notifications].reverse().map(n=>`<div class="list-item"><strong>${esc(n.title)}</strong><p>${esc(n.body)}</p><div class="meta"><span>${new Date(n.date).toLocaleString('ar-SA')}</span>${!n.read?`<button class="link-btn" onclick="readNotif(${n.id})">تعليم كمقروء</button>`:''}</div></div>`).join('')||'<div class="list-item">لا توجد إشعارات.</div>'}window.readNotif=id=>{const n=db.notifications.find(x=>x.id===id);if(n)n.read=true;save()};
$('#composeBtn').addEventListener('click',()=>openModal('رسالة جديدة',field('إلى','to')+field('الموضوع','subject')+'<label>الرسالة<textarea id="mf_body" rows="6"></textarea></label>',()=>{db.mail.push({id:uid(db.mail),box:'sent',from:'مدير النظام',to:$('#mf_to').value,subject:$('#mf_subject').value,body:$('#mf_body').value,date:new Date().toISOString()});save();toast('تم حفظ الرسالة في الصادر')}));$$('[data-mailbox]').forEach(b=>b.addEventListener('click',()=>{currentMailbox=b.dataset.mailbox;$$('[data-mailbox]').forEach(x=>x.classList.toggle('active',x===b));renderMail()}));
function renderMail(){const items=db.mail.filter(m=>m.box===currentMailbox);$('#inboxCount').textContent=db.mail.filter(m=>m.box==='inbox').length;$('#sentCount').textContent=db.mail.filter(m=>m.box==='sent').length;$('#mailList').innerHTML=[...items].reverse().map(m=>`<div class="mail-item"><strong>${esc(m.subject||'بدون موضوع')}</strong><div class="meta">${currentMailbox==='inbox'?'من: '+esc(m.from):'إلى: '+esc(m.to)} · ${new Date(m.date).toLocaleString('ar-SA')}</div><p>${esc(m.body)}</p></div>`).join('')||'<div class="mail-item">لا توجد رسائل في هذا الصندوق.</div>'}
renderAll();